### ISSUE TITLE
Create sample models for testing and use cases.

### ISSUE THREAD

**Issue by berfubuyukoz** [bounswe/bounswe2015group4#106]
Create sample models for testing and use cases. You can add data to the file in that link: https://docs.google.com/document/d/1kse027l4Xaqk90OVITMsaW5M6KIBrf7K2-XCzwmUc7w/edit?usp=sharing

**Comment by mertimre** [comment]
[users.txt](https://github.com/bounswe/bounswe2015group4/files/53178/users.txt)
[events.txt](https://github.com/bounswe/bounswe2015group4/files/53179/events.txt)
[groups.txt](https://github.com/bounswe/bounswe2015group4/files/53180/groups.txt)
