### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by oguzerdogmus** [bounswe/bounswe2015group4#113]
Erdem, can you please review my codes in commit https://github.com/bounswe/bounswe2015group4/commit/7a154ec5a722da9034737629f9b224118fa03271?

Thank you.

**Comment by erdemtoraman** [comment]
started

**Comment by erdemtoraman** [comment]
here you can find the updates according to you review
15ae5e77a82cc197cba612159cb7396458f75b75
