### ISSUE TITLE
Code Review 

### ISSUE THREAD

**Issue by erdemtoraman** [bounswe/bounswe2015group4#116]
Oguz, my commit link is the following to be reviewed.
93b04a2bd606b36be092abd141d5418bf87b4e53

**Comment by oguzerdogmus** [comment]
Hello Erdem, 

Few things I have observed about your code.
- Method commenting is missing
- Method and class naming is not consistent (e.g. there are find_common and deleteFromArray method). They all should be in same format (e.g. camelCase).
- Proper indentation is missing in some methods
- Method find_common seems to need inline comments (e.g. )
- Hard-coded strings are used while getting logger
- In some methods that have database operation, try-catch block is missing

Except the little details, the code is very well structured, easy to change and extend. Reading and understanding code are really downhill. Besides that I really like your variable naming standarts which is very hard to be consistent.

Thank you!

**Comment by erdemtoraman** [comment]
aah thank you I will be working on it.

**Comment by erdemtoraman** [comment]
I have added some documentation and got rid of indentation errors. Naming is now standardized
You may find the related commit following 
15ae5e77a82cc197cba612159cb7396458f75b75
