### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by furkancaymaz** [bounswe/bounswe2015group4#119]
Can you please review my code under commit: https://github.com/bounswe/bounswe2015group4/commit/f18dba2046cdedb5d695e66fd8943993a822c1eb

**Comment by mertimre** [comment]
Code clearity: your implementation is clear easy to understand including readable code but what I suggest is using comments sometimes. (This is also valid for myself.)

Bugs: I do not observe any bugs.

Missing features: 
events: I see nothing is missing. I believe it is the main point of this commit and it is pretty good actually.
home: Main page was missing but I know that it is now implemented pretty good. 
signup: In this one I believe you worked on fixing the parameters I do not observe huge change. I is made in better way. What is missing is user photo upload option I think.
mainHeader: You improved it well. I see nothing is missing.
mainSidebar: You improved it well also. I also think there is nothing missing.
login:nothing is missing in login, it makes pretty good checkings.
profile: You put a photopicker h.ere but it is not fully implemented.

Convention:
your indetations are good, naming is also consistent, even when you are fixing the code you change everything together. But you do not write comments which is a drawback.

.you need to add some unit testing and documentation (I believe I also need to do that ).

Your code is open to modifications. It is structured well easy to understand and make changes over it. And also making additions coherently is possible. Addition of event detail is one possibility.

My final comment about yoru commit is it is well structured. Thank you for your contribution
