### ISSUE TITLE
Missing API about the listing the groups that a user is a member of

### ISSUE THREAD

**Issue by mugekurtipek** [bounswe/bounswe2015group4#133]
We have the API "9. Listing Events to be Attended by User". We need the same type of API to show the list of Interest Groups Attended by the user.

**Comment by erdemtoraman** [comment]
Muge I believe we have this request but probably I forgot to mention it in the documentation. Anyways, started handling the situation.

**Comment by erdemtoraman** [comment]
Mugecim can you try /listMyGroups 
with a request body as follows 

{
user_token:"some_real_user_token_goes_here"
}

If it works than this issue will destroy itself in few minutes

**Comment by erdemtoraman** [comment]
oops I found out that this returns those that the user created not is a member of.

Okay now I noticed there is no way of escaping and started doing it :)

**Comment by erdemtoraman** [comment]
/listParticipatedGroups 
 Ready and deployed. request body is as expected just user_token
