### ISSUE TITLE
Cannot create an Instant_Event

### ISSUE THREAD

**Issue by erdemtoraman** [bounswe/bounswe2015group4#136]
Dear Oguz, 

I tried to create an instance event with the following user
email: erdem.toraman@boun.edu.tr

Entered random data for every field and put 25 into the field of duration.

Nothing happened and I checked the console and saw the following message.

Sevgiler kolayliklar,

![image](https://cloud.githubusercontent.com/assets/11922371/12130835/968792e8-b416-11e5-901f-32b8d8cd809b.png)

**Comment by oguzerdogmus** [comment]
Fixed.
