### ISSUE TITLE
Arranging the input fields according to their constraints

### ISSUE THREAD

**Issue by erdemtoraman** [bounswe/bounswe2015group4#80]
Oguz,

In <i> events.hmtl</i> page, you will see an input field that is supposed be used as date input, we need to be sure that it is selected from a small calendar by the user, you may use datepicker of bootstrap.Since you were working on input field restrictions I assigned this to you.

**Comment by oguzerdogmus** [comment]
It is now solved.

According to page requirements, for the future changes, the library link used in the page: http://www.daterangepicker.com/

Also, plugin allows to choose time.
