### ISSUE TITLE
Android simple profile page

### ISSUE THREAD

**Issue by berfubuyukoz** [bounswe/bounswe2015group4#85]
I am going to create a simple profile page where user can add profile picture, and user info can be seen. Events created by that user should be seen as well. (not urgent as event creation but due 02.10.2015)

**Comment by berfubuyukoz** [comment]
Started.

**Comment by tszyanalau** [comment]
Since Berfu is working on the profile page, do I need to do the edit event page layout?

**Comment by berfubuyukoz** [comment]
Hi Amy, I am working mainly on "creating an event" thing, I am also trying to create a very simple profile page to warm up in Android :) If you can create xml of "create_new_event" it would be great, so I would work on it :)

**Comment by berfubuyukoz** [comment]
Completed.
