### ISSUE TITLE
WEB | Need for sidebar

### ISSUE THREAD

**Issue by oguzerdogmus** [bounswe/bounswe2015group4#89]
Because our app is relatively simple, it seems that web project does not need sidebar menu. Furthermore, there would be more free field in web app without sidebar menu.

 Do you agree with that?

**Comment by berfubuyukoz** [comment]
I agree ,I think its possible since one can already reach to their own events or can reach event creation page via pushing the small profile picture on upper right side. We can handle reaching the groups the same way as well.
