### ISSUE TITLE
Writing the API documentation

### ISSUE THREAD

**Issue by erdemtoraman** [bounswe/bounswe2015group4#97]
Muge, you are assigned as we have talked about it already. I am writing the format down there so that we can extend the document without creating any confusion.

<b> Format of the APIDOC </b>

URL: 
Explanation:
Example Request Body:
Example Response Body:
Error Response Body:

**Comment by mugekurtipek** [comment]
Started.

**Comment by mugekurtipek** [comment]
I started to write. You can access from the link : https://github.com/bounswe/bounswe2015group4/wiki/API%20Documentation

**Comment by erdemtoraman** [comment]
Muge, I believe this issue expired. We have a working system now. So I close this one as well
